### PR TITLE
Fixes cmake policy CMP0077 build error on windows

### PR DESCRIPTION
**Pull request by SteveMoody73**
There is a cmake error when trying to build on Windows using cmake version 3.17.3. Running cmake generates the following error for ILMBASE:

> -- Configure ILMBASE Version: 2.5.3 Lib API: 25.0.2
> CMake Warning (dev) at src/ext/openexr/IlmBase/config/IlmBaseSetup.cmake:56 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'BUILD_SHARED_LIBS'.
> Call Stack (most recent call first):
>   src/ext/openexr/IlmBase/CMakeLists.txt:35 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.

When trying to building the code in Visual Studio I get multiple errors along the lines of:

> Error C2491 'Imf_2_5::TypedAttribute<Imath_2_5::Box2i>::staticTypeName': definition of dllimport function not allowed

Setting the policy CMP007 in the CMakeLists.txt file before building OpenEXR seems to resolve the issue.

### CODE REVIEW

**Comment by mmp** [comment]
Thank you!

**Comment by povmaniaco** [comment]
I have a bit different fix for EXR issue: apply the 'cmake_policy' into a setup files..
```diff
 IlmBase/config/IlmBaseSetup.cmake | 4 +++-
 OpenEXR/config/OpenEXRSetup.cmake | 4 +++-
 2 files changed, 6 insertions(+), 2 deletions(-)

diff --git a/IlmBase/config/IlmBaseSetup.cmake b/IlmBase/config/IlmBaseSetup.cmake
index 49002fb7..842e7a2d 100644
--- a/IlmBase/config/IlmBaseSetup.cmake
+++ b/IlmBase/config/IlmBaseSetup.cmake
@@ -5,7 +5,9 @@ include(GNUInstallDirs)
 
 ########################
 ## Target configuration
-
+if (POLICY CMP0077)
+  cmake_policy(SET CMP0077 NEW)
+endif()
 # This is primarily for the halfFunction code that enables a stack
 # object (if you enable this) that contains a LUT of the function
 option(ILMBASE_ENABLE_LARGE_STACK "Enables code to take advantage of large stack support"     OFF)
diff --git a/OpenEXR/config/OpenEXRSetup.cmake b/OpenEXR/config/OpenEXRSetup.cmake
index 323cae66..267e09eb 100644
--- a/OpenEXR/config/OpenEXRSetup.cmake
+++ b/OpenEXR/config/OpenEXRSetup.cmake
@@ -5,7 +5,9 @@ include(GNUInstallDirs)
 
 ########################
 ## Target configuration
-
+if (POLICY CMP0077)
+  cmake_policy(SET CMP0077 NEW)
+endif()
 # What C++ standard to compile for
 # VFX Platform 18 is c++14, so let's enable that by default
 set(tmp 14)
```
Without this, the EXR project generate a shared libs  instead static..
Cheers..
