### ISSUE TITLE
Compile errors with CUDA 11.3 on Windows

### ISSUE THREAD

**Issue by pierremoreau** [mmp/pbrt-v4#124]
I am not sure this is an error with PBRT, but be aware of it if you are considering updating to CUDA 11.3.

OS: Windows 10 Pro (Build: 19042.928)
GPU Driver: 466.11
GPU: NVIDIA GeForce RTX 3080 (+ NVIDIA GeForce GTX 1080 Ti)
CUDA: 11.3
OptiX: 7.2.0
PBRT commit: 383bc8a9eb45575180027169f14f174f9e7881b2
Config: x64-Release

```
  [7/158] Building CUDA object CMakeFiles\pbrt_lib.dir\src\pbrt\gpu\pathintegrator.cpp.obj
  FAILED: CMakeFiles/pbrt_lib.dir/src/pbrt/gpu/pathintegrator.cpp.obj 
  "D:\Program Files\NVIDIA Corporation\CUDA\v11.3\Toolkit\bin\nvcc.exe" -forward-unknown-to-host-compiler -DNOMINMAX -DPBRT_BUILD_GPU_RENDERER -DPBRT_HAS_INTRIN_H -DPBRT_HAVE__ALIGNED_MALLOC -DPBRT_IS_MSVC -DPBRT_IS_WINDOWS -DPBRT_NOINLINE=__declspec(noinline) -DPTEX_STATIC -D_CRT_SECURE_NO_WARNINGS -I"D:\Program Files\NVIDIA Corporation\CUDA\v11.3\Toolkit\include" -ID:\Softwares\pbrt-v4\src -ID:\Softwares\pbrt-v4\src\ext -ID:\Softwares\pbrt-v4\src\ext\stb -ID:\Softwares\pbrt-v4\src\ext\openexr\IlmBase\Imath -ID:\Softwares\pbrt-v4\src\ext\openexr\IlmBase\Half -ID:\Softwares\pbrt-v4\src\ext\openexr\IlmBase\Iex -ID:\Softwares\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf -Isrc\ext\openexr\IlmBase\config -Isrc\ext\openexr\OpenEXR\config -ID:\Softwares\pbrt-v4\src\ext\zlib -Isrc\ext\zlib -ID:\Softwares\pbrt-v4\src\ext\filesystem -ID:\Softwares\pbrt-v4\src\ext\ptex\src\ptex -ID:\Softwares\pbrt-v4\src\ext\double-conversion -ID:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb -I. -isystem="D:\Program Files\NVIDIA Corporation\OptiX\v7.2.0\include" -D_WINDOWS -Xcompiler="/W3 /GR /EHsc" -Xnvlink -suppress-stack-size-warning --gpu-architecture=sm_86 -Xcompiler="-MD -Zi -O2 -Ob1" -DNDEBUG -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4305 -Xcompiler /wd4552 -Xcompiler /wd4838 -Xcompiler /wd4843 -Xcompiler /wd26451 -Xcompiler /wd26495 -Xcudafe --diag_suppress=partial_override -Xcudafe --diag_suppress=virtual_function_decl_hidden -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=declared_but_not_referenced -Xcudafe --diag_suppress=implicit_return_from_non_void_function --std=c++17 --use_fast_math --expt-relaxed-constexpr --extended-lambda --forward-unknown-to-host-compiler -lineinfo -maxrregcount 128 -std=c++17 -MD -MT CMakeFiles\pbrt_lib.dir\src\pbrt\gpu\pathintegrator.cpp.obj -MF CMakeFiles\pbrt_lib.dir\src\pbrt\gpu\pathintegrator.cpp.obj.d -x cu -dc D:\Softwares\pbrt-v4\src\pbrt\gpu\pathintegrator.cpp -o CMakeFiles\pbrt_lib.dir\src\pbrt\gpu\pathintegrator.cpp.obj -Xcompiler=-FdCMakeFiles\pbrt_lib.dir\pbrt_lib.pdb,-FS
D:\Softwares\pbrt-v4\src\pbrt\util\pstd.h(357): warning : calling a __host__ function from a __host__ __device__ function is not allowed
            detected during instantiation of "pstd::span<T>::span(const V &) noexcept [with T=const pbrt::Float, V=std::vector<pbrt::Float, std::allocator<pbrt::Float>>, <unnamed>=void, <unnamed>=std::vector<pbrt::Float, std::allocator<pbrt::Float>>]" 
  D:\Softwares\pbrt-v4\src\pbrt/util/sampling.h(793): here
  
D:\Softwares\pbrt-v4\src\pbrt\util\pstd.h(357): warning : calling a __host__ function from a __host__ __device__ function is not allowed
            detected during instantiation of "pstd::span<T>::span(const V &) noexcept [with T=const pbrt::Float, V=std::vector<pbrt::Float, std::allocator<pbrt::Float>>, <unnamed>=void, <unnamed>=std::vector<pbrt::Float, std::allocator<pbrt::Float>>]" 
  D:\Softwares\pbrt-v4\src\pbrt/util/sampling.h(793): here

D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1266): warning : unrecognized #pragma in device code
D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1267): warning : unrecognized #pragma in device code
D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1271): warning : unrecognized #pragma in device code
D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1323): warning : unrecognized #pragma in device code
D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1324): warning : unrecognized #pragma in device code
D:\Softwares\pbrt-v4\src\ext\openvdb\nanovdb\nanovdb\NanoVDB.h(1328): warning : unrecognized #pragma in device code
D:\Program Files\NVIDIA Corporation\CUDA\v11.3\Toolkit\include\texture_indirect_functions.h(149): error : Internal Compiler Error (codegen): "unexpected operand in tex/surf handler"
  
  pathintegrator.cpp
  ninja: build stopped: subcommand failed.

Build All failed.
```

**Comment by mwkm** [comment]
The combo CUDA toolkit 11.3 and Optix 7.3 break on the Linux (ubuntu 20.04 on WSL2) side too.  CUDA 11.2.x & Optix 7.2 okay.

**Comment by mmp** [comment]
Unfortunately that is a regression in the CUDA 11.3 compiler (already found internally at NVIDIA; I thought it would be fixed in the CUDA 11.3 release...) For now I have added a check to the `CMakeLists.txt` file for CUDA 11.3; it is necessary to use CUDA 11.0-11.2 in the meantime. Hopefully it will be fixed in a point release...

**Comment by mmp** [comment]
@pierremoreau that's good news! The question now is now to detect 11.3.1 vs 11.3.0 in cmake...

There are `CUDA_VERSION` and `CUDA_VERSION_MINOR` in cmake, though that only gets as far as 11 and 3. There's `CUDA_VERSION_STRING`, though with 11.3.0, that seems to come out as "11.3", so I am doubtful whether it will distinguish 11.3.1... (But if you can easily check, it'd be good to know.)

**Comment by pierremoreau** [comment]
This is the change I made locally to allow it to compile with 11.3:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a59e9ea..0b89fd1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -147,7 +147,7 @@ if (CMAKE_CUDA_COMPILER)
     message (STATUS "Found CUDA: ${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}")
     if (CUDA_VERSION_MAJOR LESS 11)
       message(SEND_ERROR "pbrt-v4 requires CUDA version 11.0 or later. If you have multiple versions installed, please update your PATH.")
-    elseif (CUDA_VERSION_MINOR EQUAL 3)
+    elseif (CUDA_VERSION_MINOR EQUAL 3 AND CUDA_VERSION_PATCH EQUAL 0)
       message(SEND_ERROR "Unfortunately, pbrt-v4 triggers an internal compiler error in CUDA 11.3. Please use CUDA 11.0-11.2 until the compiler is fixed.")
     endif ()
 
```

You can have the following with CMake for version: `${*_VERSION_MAJOR}.${*_VERSION_MINOR}.${*_VERSION_PATH}.${*_VERSION_TWEAK}`.

**Comment by mmp** [comment]
Hmm, `CUDA_VERSION_PATCH` doesn't seem to be set and I can't find it in the cmake docs. I'm wondering if that worked for you since "" != 0..

I think this [patch](https://github.com/mmp/pbrt-v4/files/6565443/patch.txt) will address the issue; it sets `CUDA_VERSION_PATCH` manually. From https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html, it looks like 109 is the patch number to check for nvcc. Let me know if you have a chance to try it, @pierremoreau.

**Comment by pierremoreau** [comment]
I can confirm that your patch works. And the patch version returned is indeed 109 here.

Ah, FindCUDA does not have a `CUDA_VERSION_PATH`, indeed. FindCUDAToolkit on the other hand does. (It is supposed to be a replacement for FindCUDA for things outside the native CUDA support but was only introduced in 3.17; FindCuda has been deprecated since 3.10.)

**Comment by mmp** [comment]
Great!
