### ISSUE TITLE
Windows 10 HEAD build broken if GPU enabled

### ISSUE THREAD

**Issue by DocSavage** [mmp/pbrt-v4#100]
### Background

In checking out current head db69a23 as of Jan 17, I got errors in the compilation stage.  In looking over the commits and testing the likely candidates, I determined that the failure on my platform occurred due to commit 61933b8 when changes were made to GPUPathIntegrator.  Compilation using the preceding commit 914af26 succeeds.

I'm a CUDA newbie and haven't used C++ for a long time, so while it looks like this is due to the declaration change to `pstd::vector<LightHandle> envLights`, I'm not sure the best way to resolve the error.

### Platform

Windows 10
GeForce RTX 2060
nVidia driver 460.89
Cuda 11.2, OptiX 7.2 installed.
Visual Studio 2019

### Building

On trying Release build, I get the following errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workqueue.h	61	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workqueue.h	61	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator [subobject]") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workqueue.h	61	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workqueue.h	61	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\build\gpu_workitems_soa.h	127	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\build\gpu_workitems_soa.h	127	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator [subobject]") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\build\gpu_workitems_soa.h	127	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\build\gpu_workitems_soa.h	127	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	435	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	435	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator [subobject]") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	435	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	435	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	411	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	411	
Error		calling a __host__ function("pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector") from a __device__ function("pbrt::GPUPathIntegrator::~GPUPathIntegrator [subobject]") is not allowed	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	411	
Error		identifier "pstd::vector< ::pbrt::LightHandle,  ::pstd::pmr::polymorphic_allocator< ::pbrt::LightHandle> > ::~vector" is undefined in device code	pbrt_lib	C:\Users\billk\pbrt-v4\src\pbrt\gpu\workitems.h	411	
```

**Comment by povmaniaco** [comment]
I can confirm that the GPU build fail also here. Windows 10 Pro, Cuda 11.1, Optix 7.2 and the same NVidia driver: 460.89

**Comment by mmp** [comment]
@povmaniaco with the same error message? It builds fine with CUDA 11.1 on Linux, and I'd assume this would be consistent across CUDA versions.

In any case, I'll try upgrading to 11.2 and see if I can reproduce it here.

**Comment by povmaniaco** [comment]
Yes, @mmp  with the same message. I also want to update to CUDA 11.2 here

**Comment by povmaniaco** [comment]
Yeah.. It is really frustrating that the GPU mode does not work in Windows, and even more so, when it works correctly (and very fast..) under Linux  :(

**Comment by mmp** [comment]
So I can confirm that this doesn't happen with CUDA 11.2 on Linux, at least. This is very puzzling though, since it clearly seems to be coming from nvcc, which should behave the same on both..

Unfortunately I'm not going to be able to chase this down myself in the near future, but as always, PRs welcome!

**Comment by povmaniaco** [comment]
I have upgraded to Cuda 11.2 and the problem persists on Windows. After investigating the error messages, I think I am not proficient in Cuda to try to fix the problem. I'm sorry..

**Comment by pierremoreau** [comment]
I can reproduce and I will try to look at this issue over the weekend. It is interesting that it only occurs in Release mode and not Debug.

**Comment by pierremoreau** [comment]
Explicitly defining a destructor for `GPUPathIntegrator` “fixes” the compilation error.

Now how as to why it is looking for a `__device__` destructor for `pstd::vector<pbrt::LightHandle>`: methods like `GPUPathIntegrator::HandleEscapedRays()` use `PBRT_GPU_LAMBDA()` which uses a `*this*` capture, i.e. capturing the current object by copy meaning the destructor of `GPUPathIntegrator` will be called when exiting `PBRT_GPU_LAMBDA()`. Note how Windows and Linux defaults there:

```c++
#ifdef PBRT_IS_WINDOWS
#define PBRT_GPU_LAMBDA(...) [ =, *this ] PBRT_GPU(__VA_ARGS__) mutable
#else
#define PBRT_GPU_LAMBDA(...) [=] PBRT_GPU(__VA_ARGS__)
#endif
```

@mmp Is it really meant to do a capture by copy?

**Comment by pierremoreau** [comment]
Ah, I see `GPURender()` explains why `*this` is captured that way on Windows, makes sense.

**Comment by povmaniaco** [comment]
Nice job!

**Comment by mmp** [comment]
A-ha! Nice find.

I was trying to imagine why on Windows that destructor would be invoked but couldn't come up with a scenario. I had forgotten about that.

Shall I go ahead an add an empty destructor then? With that, does the build fully work again? (And, dare I ask, does it run?)

**Comment by pierremoreau** [comment]
I haven’t tested running it yet, but adding an explicit destructor to `GPUPathIntegrator()` did allow PBRT to fully build.

However I believe this is only a workaround and not a proper fix, which would be to get the `pstd::vector` to work for device code or avoid the constructor and destructor of `pstd::vector` being called at all to start with.

**Comment by mmp** [comment]
@pierremoreau one workaround to avoid the constructor/destructor could be to store a pointer to the vector, `pstd::vector<LightHandle> *envLights`, in `GPUPathIntegrator`. (Slightly unfortunate to add the level of indirection, but probably the most expedient solution.)

**Comment by pierremoreau** [comment]
I could try that later today or tomorrow; would probably need two pointers: one CPU and one GPU due to being for the non-uniform-memory scenario.

Also I will try going through all those warnings about host functions called from host + device ones, like mentioned in #104; I wonder if that could be causing the crashes we see on Windows.

**Comment by mmp** [comment]
I think one pointer and having the vector in unified memory is actually ok: the CPU doesn't need to access the pointer itself (or what it points to) during rendering. That whole `*this` capture hack is only due to the CPU reading `maxDepth` and a few other `PathIntegrator` member variables during rendering. Arguably a better fix would be to fix the CPU code to not do that in the first place, but I'm not sure it's worth the bother.

**Comment by povmaniaco** [comment]
@pierremoreau I have some free time today.. let me know when you pushed some chnages. I can try to compile under Windows. 10

**Comment by DocSavage** [comment]
@pierremoreau Whenever you push changes, I'll see if that works on my platform as well.  Thanks for the debugging and mods!

**Comment by pbrt4bounty** [comment]
@mmp Cuda build Ok with the last changes. Go to make a render test..

**Comment by pierremoreau** [comment]
With the commit Matt uploaded, it seems to compile fine here but then crashes while running, similarly to #41.

**Comment by pbrt4bounty** [comment]
I'm also get a lot of messages like this:
```bash
CUDALINK : nvlink warning : Stack size for entry function '_ZN4pbrt6KernelIZNS_12ForAllQueuedIZNS_17GPUPathIntegrator23EvaluateMaterialAndBSDFINS_22ThinDielectricMaterialENS_25UniversalTextureEvaluatorEEEvT0_PNS_14MultiWorkQueueINS_8TypePackIJNS_20MaterialEvalWorkItemINS_21CoatedDiffuseMaterialEEENS9_INS_23CoatedConductorMaterialEEENS9_INS_17ConductorMaterialEEENS9_INS_18DielectricMaterialEEENS9_INS_15DiffuseMaterialEEENS9_INS_27DiffuseTransmissionMaterialEEENS9_INS_12HairMaterialEEENS9_INS_16MeasuredMaterialEEENS9_INS_18SubsurfaceMaterialEEENS9_IS4_EENS9_INS_11MixMaterialEEEEEEEEiEUlSS_E_SS_EEvPKcPNS_9WorkQueueIS6_EEiT_EUliE_EEvS14_i' cannot be statically determined [D:\REPOS\pbrt-v4\build_cuda\pbrt_lib.vcxproj]
```

**Comment by mmp** [comment]
Hmm. Those warnings are benign and in fact the build configuration [sets a flag to suppress them](https://github.com/mmp/pbrt-v4/blob/master/CMakeLists.txt#L184).

So I wonder why you are seeing them. I wonder if this is a clue that part of the problem here is that on Windows other, more important, build flags also aren't being passed through.

**Comment by pbrt4bounty** [comment]
> 
> 
> Hmm. Those warnings are benign and in fact the build configuration [sets a flag to suppress them](https://github.com/mmp/pbrt-v4/blob/master/CMakeLists.txt#L184).
> 
> So I wonder why you are seeing them. I wonder if this is a clue that part of the problem here is that on Windows other, more important, build flags also aren't being passed through.

@mmp  Maybe the first case need to use 'set', instead 'string', and use string(APPEND "any_other_option") for the others..?
```bash
    # Willie hears yeh..
    set (CMAKE_CUDA_FLAGS "-Xnvlink -suppress-stack-size-warning")
....
....
    string (APPEND CMAKE_CUDA_FLAGS " --gpu-architecture=${ARCH}")
...
```
I'm checking now..
Cheers..

**Comment by povmaniaco** [comment]
@mmp I'm are investigating a bit this error under Windows with GPU and i was wondering if is this code correct ??  https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/gpu/accel.cpp#L1188
```cpp
        OPTIX_CHECK(optixLaunch(optixPipeline, cudaStream, pbs.ptr,
                                sizeof(RayIntersectParameters), &shadowSBT, maxRays, 1,
                                1));
        CUDA_CHECK(cudaEventRecord(pbs.finishedEvent));
```

Here, the format seems different.
https://raytracing-docs.nvidia.com/optix7/guide/index.html#ray_generation_launches#ray-generation-launches

```cpp
optixLaunch(pipeline, stream, 
    d_pipelineParams, sizeof(MyPipelineParams), 
    &sbt, width, height, depth);
```
I meant this because this code line appear in the error message..
```batch
[ 11012.000 20210220.112048 D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:556 ] 
ERROR OptiX: ERROR: Error recording event to prevent concurrent launches on the same OptixPipeline (CUDA error string: an illegal memory access was encountered, CUDA error code: 700)
Error recording resource event on user stream (CUDA error string: an illegal memory access was encountered, CUDA error code: 700)
[ 11012.000 20210220.112048 D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:1189 ] FATAL OptiX call optixLaunch(optixPipeline, cudaStream, pbs.ptr, sizeof(RayIntersectParameters), &shadowSBT, 1, 1, 1) failed with code 7900: "CUDA error"
```

Hope this can help you..
Cheers..

**Comment by povmaniaco** [comment]
@mmp I continue my search..
 With a simple `printf` into pbrt code, this show that `maxRays` is the product of `render width * render height`, and in the accel.cpp code, if we follow the optix documentation about the format of `optixLaunch` method, this is asigned to 'width',  that not seems very coherent.
So..
Follow this example from Ingo Wald.. https://github.com/ingowald/optix7course/blob/master/example02_pipelineAndRayGen/SampleRenderer.cpp#L360
```cpp
OPTIX_CHECK(optixLaunch(/*! pipeline we're launching launch: */
                            pipeline,stream,
                            /*! parameters and SBT */
                            launchParamsBuffer.d_pointer(),
                            launchParamsBuffer.sizeInBytes,
                            &sbt,
                            /*! dimensions of the launch: */
                            launchParams.fbSize.x,
                            launchParams.fbSize.y,
                            1
                            ));
 ```
I made a couple of changes in the pbrt-4 accel.cpp code lines 1150 and 1189
```cpp

        OPTIX_CHECK(optixLaunch(optixPipeline, cudaStream, pbs.ptr,
                                sizeof(RayIntersectParameters), &intersectSBT, 640, 480,
                                1));
        CUDA_CHECK(cudaEventRecord(pbs.finishedEvent));
```
..and create a simple scene example with this 640 * 480 format and !! voila !!
GPU render work in Windows!!

**Comment by mmp** [comment]
Thanks for digging into this!

As far as I understand it, the whole "width", "height", and "depth" stuff in `optixLaunch` is a convenience for applications. In other words, if you're tracing one ray for every pixel, then you can launch (width, height, 1) and then it's easy to associate pixel coordinates with rays in the optix code. pbrt doesn't have a direct relation between pixels and rays like that (e.g. because some paths get terminated), so it does a 1D launch with the maximum number of rays it may need to trace.

Then, in optix code, pbrt only uses [the first dimension](https://github.com/mmp/pbrt-v4/blob/09ea972a7a76588db6a176712f7834d8ba5a219d/src/pbrt/gpu/optix.cu#L95) for indexing into its buffer of rays. So, launching (640, 480, 1) will end up repeatedly doing the work for the first 640 rays only.

Now, that said, this is a very interesting clue! There is apparently some issue of insufficient memory allocation / invalid indexing past the end of an allocation. The fact that it runs successfully only accessing the first 640 elements of the various buffers definitely helps narrow down the possibilities. (I remain unsure why it would only happen on windows, but one step at a time...) I will review all of that code with this clue in mind...

**Comment by mmp** [comment]
This is a shot in the dark, but could you try modifying the `bypassSlab()` method at line 51 of `src/pbrt/util/memory.h` to always return `true` and see if that fixes the release build?

**Comment by povmaniaco** [comment]
No luck. Same error. But i made only a 'rebuild' after add these change. Let me make now a totally fresh build to make sure.

**Comment by povmaniaco** [comment]
Yes. Also from a fresh build, same error and referring the same line:
```batch
20210220.204150 D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:556 ] ERROR OptiX: ERROR: Error recording event to prevent concurrent launches on the same OptixPipeline (CUDA error string: an illegal memory access was encountered, CUDA error code: 700)
Error recording resource event on user stream (CUDA error string: an illegal memory access was encountered, CUDA error code: 700)
[ 1916.000 20210220.204150 D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:1190 ] FATAL OptiX call optixLaunch(optixPipeline, cudaStream, pbs.ptr, sizeof(RayIntersectParameters), &shadowSBT, maxRays, 1, 1) failed with code 7900: "CUDA error"
```

**Comment by povmaniaco** [comment]
@mmp Another clue.. Building the last repo splash, under Windows, with this options:
```cmake
cmake -G "Visual Studio 16 2019" ../ ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DPBRT_FLOAT_AS_DOUBLE="ON" ^
 -DPBRT_NVTX="ON" ^
 -DPBRT_OPTIX7_PATH=D:/CUDA/OptiXSDK720 ^
 -DFORCE_GPU_BUILD="ON" ^
 -DCMAKE_INSTALL_PREFIX=D:/REPOS/pbrt-v4/build_pbrt4
```
The crash goes out. No render, but not crash..
The entire process, from export scene to render is finished without crash.
```batch
INIT PBRT4 RENDER ENGINE..
There is not any node connected. Check your nodes for Glass
Export completed in 0.00501 to D:/tmp/Plane.ply
Export completed in 0.05995 to D:/tmp/Circle.ply
pbrt version 4 (built Feb 28 2021 at 05:50:05)
Copyright (c)1998-2020 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [                                                                                                  ]  (5.6s|?s)
DEL PBRT4 RENDER ENGINE..
```
I hoppe this help you.
Cheers

**Comment by povmaniaco** [comment]
Ok. 
Rectification.. the error does not occur when calling pbrt.exe from within Blender. This in some way avoids the interruption of pbrt. If run from the command line, the error reoccurs.

**Comment by povmaniaco** [comment]
But a bit different.. Execution stops after 138 seconds. No image is written to disk and `cuda-memcheck` produces the attached result.
[cuda_memcheck_backtrace.txt](https://github.com/mmp/pbrt-v4/files/6056363/cuda_memcheck_backtrace.txt)

Cheers..

**Comment by povmaniaco** [comment]
Seems that after the last commit, the GPU build under Windows seems to work now. Although the result of the render is a black image, at least pbrt is not crashed. Can anyone confirm this?
```batch
Export completed in 0.02276 to E:/tmp/Cube.ply
Export completed in 0.0288 to E:/tmp/Cube.001.ply
Export completed in 0.001 to E:/tmp/Plane.001.ply
pbrt version 4 (built Apr 27 2021 at 23:24:39)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++]  (15.0s)
GPU Kernel Profile:
  Generate Camera rays                              8 launches    201.56 ms /   1.4% (avg 25.195, min 23.608, max  27.955)
  Generate ray samples - HaltonSampler             32 launches    133.12 ms /   0.9% (avg  4.160, min  3.574, max   6.098)
  Tracing closest hit rays                         32 launches  11270.90 ms /  75.8% (avg 352.216, min 187.126, max 424.511)
  ConductorMaterial + BxDF Eval (Basic tex)        24 launches     78.36 ms /   0.5% (avg  3.265, min  3.069, max   4.624)
  DiffuseMaterial + BxDF Eval (Basic tex)          24 launches    797.60 ms /   5.4% (avg 33.233, min 30.885, max  39.657)
  Tracing shadow rays                              24 launches   2367.00 ms /  15.9% (avg 98.625, min 90.339, max 109.934)
  Update Film                                       8 launches     25.80 ms /   0.2% (avg  3.225, min  2.898, max   5.471)
  Other                                           128 launches      2.25 ms /   0.0% (avg  0.018)

Total GPU time:  14876.58 ms

GPU Statistics:
    Camera rays                                                 7372800
    Indirect rays, depth 1                                      7372800
    Indirect rays, depth 2                                      7372800
    Indirect rays, depth 3                                      7372800
    Shadow rays, depth 0                                        3602030
    Shadow rays, depth 1                                        3686056
    Shadow rays, depth 2                                        3478770
```

**Comment by pierremoreau** [comment]
I’m unable to test against the latest HEAD, but I was able to compile, run and properly render killeroo-gold 10 days ago on Windows thanks to 5d5a732 (see https://github.com/mmp/pbrt-v4/issues/89#issuecomment-822007437).

**Comment by povmaniaco** [comment]
> Could it be that you end up with logging being enabled in the GPU-case but not in the CPU-case?

I don't understand what do you meant... I use the same scene, with the same render call, that I only added --gpu option

**Comment by pierremoreau** [comment]
> > Could it be that you end up with logging being enabled in the GPU-case but not in the CPU-case?
> 
> I don't understand what do you meant... I use the same scene, with the same render call, that I only added --gpu option

Some of the recent patches pushed to pbrt-v4 have been about logging when using the GPU, and I wonder if a bug might have been introduced resulting in logging being enabled when using the GPU, even if the user never asked for it.

Finding where most of the time is being spent might help in finding the issue.

**Comment by pbrt4bounty** [comment]
No luck.. always a black render result.  @pierremoreau can you share the specific killeroo scene that work for you in Windows??
Is from the repository??
Because the question is: why does it work in that scene and not in others? For the materials? the lights.. what?
Thanks in advance..

**Comment by pierremoreau** [comment]
@pbrt4bounty I am using this one: https://github.com/mmp/pbrt-v4-scenes/blob/master/killeroos/killeroo-gold.pbrt.

Matt is aware that it does not work for all scenes yet, as noted back in this commit: 5d5a73245dfb49f6da1a30ee2dc3b5f6da1ea770.

**Comment by pbrt4bounty** [comment]
OK.. I have managed to get it to work with other scenes after turning 'OFF' the 'PBRT_NVTX' option that I had previously activated.
The binary that I used is build with Optix 7.2 / CUDA 11.2 under Windows 10, rom the last 'master'
[bmw_3_blender.zip](https://github.com/mmp/pbrt-v4/files/6405227/bmw_3_blender.zip)
This is the scene, exported from Blender using the 'proof of concept' addon in which i am working.

**Comment by pbrt4bounty** [comment]
Btw.. the speed difference is really amazing!!
```
pbrt e:/bmw/tmp.pbrt
pbrt version 4 (built Apr 30 2021 at 10:41:01)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [++++++++++++++++++++++++++++++++++++++++++++++]  (132.1s)

pbrt --gpu e:/bmw/tmp.pbrt
pbrt version 4 (built Apr 30 2021 at 10:41:01)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [++++++++++++++++++++++++++++++++++++++++++++++]  (4.9s)
```
:)

**Comment by mmp** [comment]
@pbrt4bounty that's an interesting datapoint about PBRT_NVTX. Though I am still seeing crashes (also CUDA 11.2, OptiX 7.2, Windows 10) for many scenes even with that disabled. Does it work for everything for you? e.g. could you try villa-lights-on.pbrt in the pbrt-v4-scenes distribution?

**Comment by pbrt4bounty** [comment]
Hi @mmp  I'm testing quite a few scenes here ( with the Blender addon..) and so far, I haven't had any problems. But you are right, it's a good idea, to test it with one of the 'official' scenes.

**Comment by pbrt4bounty** [comment]
@mmp  Ok. Villa produce this error here:
```batch
pbrt version 4 (built May  1 2021 at 16:51:28)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [                                                          ]  (0.1s|?s)
(2920,   0,   0) error: encountered ray with nan or inf values:
(2921,   0,   0) error: encountered ray with nan or inf values:
(2922,   0,   0) error: encountered ray with nan or inf values:
(2923,   0,   0) error: encountered ray with nan or inf values:
(2931,   0,   0) error: encountered ray with nan or inf values:
Rendering: [                                                           ]  (0.3s|?s) 
[ tid 000 @     0.000s D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:567 ] 
    ERROR OptiX: ERROR: Validation mode caught builtin exception OPTIX_EXCEPTION_CODE_INVALID_RAY
Error recording resource event on user stream (CUDA error string: unspecified launch failure, CUDA error code: 719)
[ tid 000 @     0.000s D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:1204 ]
    FATAL OptiX call optixLaunch(optixPipeline, cudaStream, pbs.ptr, sizeof(RayIntersectParameters), &intersectSBT, maxRays, 1, 1)
	failed with code 7053: "Error during validation mode run"
```
I hope help you..

**Comment by pbrt4bounty** [comment]
This error reference this code.. D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:1204
```cpp
    gasInstance.flags =
        OPTIX_INSTANCE_FLAG_NONE;  // TODO: OPTIX_INSTANCE_FLAG_DISABLE_ANYHIT
    if (triangleGASTraversable) {
        gasInstance.traversableHandle = triangleGASTraversable;
        gasInstance.sbtOffset = 0; // line 1204
        iasInstances.push_back(gasInstance);
    }
````
..that make a bit sense: the scene contain instances
Cheers..

**Comment by pbrt4bounty** [comment]
This are the  error message from lite orbe scene..
```batch
E:\apps\pbrt4>pbrt --gpu D:\REPOS\pbrt-v4-scenes\lte-orb\orb.pbrt
pbrt version 4 (built May  1 2021 at 16:51:28)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
(9019,   0,   0) error: encountered ray with nan or inf values:
       origin:          [0.000647, -0.492945, 0.390995]
       direction:       [nan, nan, nan]
       tmin:            0.000000
       tmax:            1000000015047466219876688855040.000000
       rayTime:         0.000000
       call location: No source location available. The input PTX may not contain debug information (nvcc option: -lineinfo),
OptixModuleCompileOptions::debugLevel set to OPTIX_COMPILE_DEBUG_LEVEL_NONE, or no useful information is present
for the current block.
(22854,   0,   0) error: encountered ray with nan or inf values:
tid 000 @     0.000s D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:567 ]
ERROR OptiX: ERROR: Validation mode caught builtin exception OPTIX_EXCEPTION_CODE_INVALID_RAY
Error recording resource event on user stream (CUDA error string: unspecified launch failure, CUDA error code: 719)
[ tid 000 @     0.000s D:/REPOS/pbrt-v4/src/pbrt/gpu/accel.cpp:1204 ]
FATAL OptiX call optixLaunch(optixPipeline, cudaStream, pbs.ptr, sizeof(RayIntersectParameters), &intersectSBT, maxRays, 1, 1)
failed with code 7053: "Error during validation mode run"
```

**Comment by pbrt4bounty** [comment]
After verifying that of the 'official' scenes only killeros gold is rendered in GPU mode in the windows compilation, I have the feeling that the problem is in some aspect of these scenes, that it is not processed correctly in GPU mode under Windows. On the other hand, the scenes generated with the Blender exporter are rendered in GPU mode. And not just simple scenes. Complex scenes are also rendered, like the Barcelona Pavilion. What do you think, @mmp ??

**Comment by pbrt4bounty** [comment]
Some updateds:
-  after merge the last changes, I try to render villa scene  again, and I obtain this error:
```batch
D:\REPOS\pbrt-v4\deploy\bin>pbrt --gpu --spp 4 E:\devs\pbrt-v4-scenes\villa\villa.pbrt
pbrt version 4 (built May  3 2021 at 10:21:11)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
[ tid 000 @     0.000s D:/REPOS/pbrt-v4/src/pbrt/gpu/aggregate.cpp:132 ] FATAL CUDA error: unspecified launch failure
```
By other hand, the 'book' scene is also properly rendered in GPU mode ( as killeroos-gold..). 
Cheers..

**Comment by mmp** [comment]
With the latest commit, everything(*) seems to be working on Windows now.

Embarrassingly, the issue was right there in the compiler warnings: GPU code calling std::copysign (et al.), so 597fc75 was all it took. In my defense, something seems to have changed in that those calls didn't cause any trouble with earlier versions of CUDA/MSVC. In any case, everything I've tried renders successfully now 🎉 . I will leave this issue open for now, pending confirmation from others..

(*) There is a performance issue, filed as a separate issue, #128.

**Comment by DocSavage** [comment]
Thanks very much for the fix.  I can confirm the ability to build and run in `--gpu` mode without issue.
On my Ryzen 5 2600X CPU, RTX 2060 computer, I got 94.5 seconds rendering explosion.pbrt and with `--gpu` it was 9.2 seconds.

**Comment by mmp** [comment]
Closing this out; whew.

(@DocSavage performance should be much improved from that with the just checked in cb78c6494576059c7ba1e3a48dc73965cc981499.)
